<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-6T0AJC6" failures="1" tests="1" name="loginFallido_02" time="1.641" errors="0" timestamp="2023-07-17T15:00:11 ART">
  <testcase classname="tests.LoginTest" name="loginFallido_02" time="0.252">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at tests.LoginTest.loginFallido_02(LoginTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- loginFallido_02 -->
  <testcase classname="tests.LoginTest" name="loginValido_01" time="0.0">
    <ignored/>
  </testcase> <!-- loginValido_01 -->
</testsuite> <!-- loginFallido_02 -->
